
server:
  port: 0


spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/jass_database
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka