eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost

server:
  port: 8000

spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/{*segments}

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/{*segments}
          filters:
            - name: AddEmailAndIdHeaderFilter

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/profile/{*segments}
          filters:
            - name: AddEmailAndIdHeaderFilter

        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/api/v1/image/getImage/{*segments}
          filters:
            - name: AddEmailAndIdHeaderFilter

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/v1/event/{*segments}
          filters:
            - name: AddEmailAndIdHeaderFilter

  main:
    web-application-type: REACTIVE
    allow-bean-definition-overriding: true
