eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-root
            uri: lb://auth-service
            predicates:
              - Path=/api/v1/auth/{*segments}
